services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Taskboarddb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=john
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Taskboarddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: john
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
